codon_table = {
'ttt': ('Phenylalanine', 'Phe', 'F', 'nonpolar'),
'ttc': ('Phenylalanine', 'Phe', 'F', 'nonpolar'),
'tta': ('Leucine', 'Leu', 'L', 'nonpolar'),
'ttg': ('Leucine', 'Leu', 'L', 'nonpolar'),
'ctt': ('Leucine', 'Leu', 'L', 'nonpolar'),
'ctc': ('Leucine', 'Leu', 'L', 'nonpolar'),
'cta': ('Leucine', 'Leu', 'L', 'nonpolar'),
'ctg': ('Leucine', 'Leu', 'L', 'nonpolar'),
'att': ('Isoleucine', 'Ile', 'I', 'nonpolar'),
'atc': ('Isoleucine', 'Ile', 'I', 'nonpolar'),
'ata': ('Isoleucine', 'Ile', 'I', 'nonpolar'),
'atg': ('Methionine', 'Met', 'M', 'nonpolar (start)'),
'gtt': ('Valine', 'Val', 'V', 'nonpolar'),
'gtc': ('Valine', 'Val', 'V', 'nonpolar'),
'gta': ('Valine', 'Val', 'V', 'nonpolar'),
'gtg': ('Valine', 'Val', 'V', 'nonpolar'),
'tct': ('Serine', 'Ser', 'S', 'polar'),
'tcc': ('Serine', 'Ser', 'S', 'polar'),
'tca': ('Serine', 'Ser', 'S', 'polar'),
'tcg': ('Serine', 'Ser', 'S', 'polar'),
'cct': ('Proline', 'Pro', 'P', 'nonpolar'),
'ccc': ('Proline', 'Pro', 'P', 'nonpolar'),
'cca': ('Proline', 'Pro', 'P', 'nonpolar'),
'ccg': ('Proline', 'Pro', 'P', 'nonpolar'),
'act': ('Threonine', 'Thr', 'T', 'polar'),
'acc': ('Threonine', 'Thr', 'T', 'polar'),
'aca': ('Threonine', 'Thr', 'T', 'polar'),
'acg': ('Threonine', 'Thr', 'T', 'polar'),
'gct': ('Alanine', 'Ala', 'A', 'nonpolar'),
'gcc': ('Alanine', 'Ala', 'A', 'nonpolar'),
'gca': ('Alanine', 'Ala', 'A', 'nonpolar'),
'gcg': ('Alanine', 'Ala', 'A', 'nonpolar'),
'tat': ('Tyrosine', 'Tyr', 'Y', 'polar'),
'tac': ('Tyrosine', 'Tyr', 'Y', 'polar'),
'taa': ('Ochre', '', '', 'stop'),
'tag': ('Amber', '', '', 'stop'),
'cat': ('Histidine', 'His', 'H', 'basic'),
'cac': ('Histidine', 'His', 'H', 'basic'),
'caa': ('Glutamine', 'Gln', 'Q', 'polar'),
'cag': ('Glutamine', 'Gln', 'Q', 'polar'),
'aat': ('Asparagine', 'Asn', 'N', 'polar'),
'aac': ('Asparagine', 'Asn', 'N', 'polar'),
'aaa': ('Lysine', 'Lys', 'K', 'basic'),
'aag': ('Lysine', 'Lys', 'K', 'basic'),
'gat': ('Aspartic acid', 'Asp', 'D', 'acidic'),
'gac': ('Aspartic acid', 'Asp', 'D', 'acidic'),
'gaa': ('Glutamic acid', 'Glu', 'E', 'acidic'),
'gag': ('Glutamic acid', 'Glu', 'E', 'acidic'),
'tgt': ('Cysteine', 'Cys', 'C', 'polar'),
'tgc': ('Cysteine', 'Cys', 'C', 'polar'),
'tga': ('Opal', '', '', 'stop'),
'tgg': ('Tryptophan', 'Trp', 'W', 'nonpolar'),
'cgt': ('Arginine', 'Arg', 'R', 'basic'),
'cgc': ('Arginine', 'Arg', 'R', 'basic'),
'cga': ('Arginine', 'Arg', 'R', 'basic'),
'cgg': ('Arginine', 'Arg', 'R', 'basic'),
'agt': ('Serine', 'Ser', 'S', 'polar'),
'agc': ('Serine', 'Ser', 'S', 'polar'),
'aga': ('Arginine', 'Arg', 'R', 'basic'),
'agg': ('Arginine', 'Arg', 'R', 'basic'),
'ggt': ('Glycine', 'Gly', 'G', 'nonpolar'),
'ggc': ('Glycine', 'Gly', 'G', 'nonpolar'),
'gga': ('Glycine', 'Gly', 'G', 'nonpolar'),
'ggg': ('Glycine', 'Gly', 'G', 'nonpolar')}
